name       : bookworm
version    : 1.0.0
release    : 1
source     :
    - https://github.com/babluboy/bookworm/archive/1.0.0.tar.gz : 8dacaab3531c189836f7ef65dc69a84de9d03e467e68275bb6c5a31b17f9fbc5
license    : GPL-3.0
component  : office.viewers
summary    : A simple ebook reader
description: |
    Read the books you love without having to worry about the different format complexities like epub, pdf, mobi, cbr, etc. This version supports EPUB, PDF and Comics (CBR and CBZ) formats with support for more formats to follow soon.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(poppler-glib)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - poppler-utils
    - vala
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
